title:    "Lite App Manifests"
tagline:  "Lite Apps for use with Hermit: https://hermit.chimbori.com/"
url:      "https://lite-apps.chimbori.com"
cdn_url:  "https://lite-apps.chimbori.com"
exclude:  [
            # Don’t add an exclusion for *.jsx, the JSX is compiled to JS inside the _site directory.
            "*.bat",
            "*.gradle",
            "*.properties",
            "*.sh",
            "blocklists/src",
            "Gemfile",
            "Gemfile.lock",
            "lite-apps/src",
            "gradle.properties",
            "gradle/",
            "gradlew",
            "local.properties",
            "node_modules/",
            "package.json",
            "schema/",
            "settings.gradle",
            "tools/"
          ]
minify_html: true
sass:
  style: compressed
